apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  selector:
    # 这里需要注意的是,需要配置spec.template.metadata.labels的键值完成配置
    # 如果是在idea那里,注意一下左边的那个小箭头,可以点一下,会有提示的
    matchLabels:
      app: tomcat
  replicas: 3
  # 一般情况下是不会直接编写Pod的配置文件的,而是通过Deployment来控制pod,比如副本数等等,需要非常注意的是标签选择器的总是,需要对应起来
  # 而且是需要通过左边的小箭头确认最好了
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat-pod
          image: tomcat:8.5-jre8
          imagePullPolicy: IfNotPresent
          ports:
            - name: tomcat-port
              containerPort: 8080
  