apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  namespace: default
  labels:
    name: tomcat8
spec:
  containers:
    - name: tomcat
      image: tomcat:8.5-jre8
      imagePullPolicy: IfNotPresent
      ports:
        - name: tomcat-port
          containerPort: 8080
          