server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=true
      driver: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      initial-size: 1 #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时，默认值为0
      min-idle: 1     #最小连接池的数量，默认值为空，应该是0，留待后面确认
      max-active: 8   #最大连接池的数量，默认值为8
      max-wait: 60000 #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁
      keep-alive: true #连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作。默认false(保活)

